# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.17'

    - name: Export
      run: export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
      
    - name: Build
      run: go build -v main.go
      
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ssh-testing.alwaysdata.net
        username: testing_test
        password: ${{ secrets.PASSWORD }}
        source: "main"
        target: ~/

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ssh-testing.alwaysdata.net
        username: testing_test
        password: ${{ secrets.PASSWORD }}
        script: |
          export BOT_TOKEN=${{ secrets.BOT_TOKEN }} 
          ./main
